import { Cpu, FileText, BarChart3, Cog, Send, Sparkles, Loader2, Copy, Check, RotateCcw } from 'lucide-react'
import { useState } from 'react'
import ResultCards from './components/ResultCards'
import LoadingSkeleton from './components/LoadingSkeleton'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'

const useCases = [
  { icon: FileText, title: 'Document Intelligence', desc: 'AI-powered extraction from any document format' },
  { icon: BarChart3, title: 'Predictive Analytics', desc: 'Forecasts, risk scores, and actionable dashboards' },
  { icon: Cog, title: 'Process Automation', desc: 'Intelligent RPA that learns and scales' },
]

const quickPrompts = [
  { label: 'FMCG company struggling with reporting', full: 'FMCG company struggling with reporting' },
  { label: 'Healthcare: 50K+ disconnected patient records', full: 'Healthcare chain managing 50,000+ patient records across 12 disconnected systems with no unified view' },
  { label: 'Finance: 200+ hrs/month invoice checks', full: 'Financial services firm spending 200+ hours/month manually cross-checking vendor invoices against procurement contracts' },
]

function formatAsMarkdown(data) {
  let md = `## Executive Synthesis\n${data.executive_synthesis}\n\n`
  md += `## Strategic Roadmap\n`
  data.strategic_roadmap.forEach(phase => {
    md += `### ${phase.phase} — ${phase.title}\n`
    md += `${phase.description}\n`
    md += `**Technologies:** ${phase.key_technologies.join(', ')}\n\n`
  })
  md += `## Business Impact\n\n**ROI Metrics:**\n`
  data.business_impact.roi_metrics.forEach(m => { md += `• ${m}\n` })
  md += `\n**Cost of Inaction:**\n`
  data.business_impact.cost_of_inaction.forEach(c => { md += `• ${c}\n` })
  md += `\n---\n*Generated by Chiacon AI Lab — chiacon.com*`
  return md
}

function CopyButton({ data }) {
  const [copied, setCopied] = useState(false)
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatAsMarkdown(data))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* fallback */ }
  }
  return (
    <button onClick={handleCopy}
      style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '7px 14px', borderRadius: '7px', fontSize: '12px', fontWeight: 600, background: copied ? '#ecfdf5' : 'var(--bg-white)', color: copied ? '#059669' : 'var(--text-heading)', border: `1px solid ${copied ? '#a7f3d0' : 'var(--border-strong)'}`, cursor: 'pointer', transition: 'all 0.2s', fontFamily: 'inherit', boxShadow: 'var(--shadow-sm)' }}>
      {copied ? <Check style={{ width: '12px', height: '12px' }} /> : <Copy style={{ width: '12px', height: '12px' }} />}
      {copied ? 'Copied!' : 'Copy Results'}
    </button>
  )
}

export default function App() {
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')

  const handleSubmit = async (problemText) => {
    const problem = problemText || input
    if (!problem.trim()) return
    setLoading(true); setResult(null); setError('')
    try {
      const res = await fetch(`${API_URL}/api/generate`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ business_problem: problem }),
      })
      if (!res.ok) throw new Error(`Error: ${res.status}`)
      setResult(await res.json())
    } catch (err) {
      setError('Could not reach the AI service. Please try again.')
    } finally { setLoading(false) }
  }

  const handleQuickPrompt = (p) => { setInput(p.full); handleSubmit(p.full) }

  return (
    <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', background: 'var(--bg)' }}>
      {/* ===== Navbar ===== */}
      <nav style={{ background: 'var(--navy)', padding: '0 32px', height: '52px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{ width: '30px', height: '30px', borderRadius: '6px', background: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '3px' }}>
            <img src="/chiacon-icon.png" alt="Chiacon" style={{ height: '22px', objectFit: 'contain' }} />
          </div>
          <span style={{ fontSize: '16px', fontWeight: 700, color: 'white', letterSpacing: '0.08em' }}>CHIACON</span>
          <span style={{ fontSize: '10px', fontWeight: 600, color: 'var(--teal)', background: 'rgba(17,179,165,0.15)', padding: '2px 6px', borderRadius: '3px' }}>AI LAB</span>
        </div>
        <span style={{ fontSize: '12px', color: 'rgba(255,255,255,0.5)' }}>Pioneering IT Services & Consulting</span>
      </nav>

      {/* ===== Main Content ===== */}
      <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>

        {/* ===== LEFT PANEL ===== */}
        <div style={{
          width: '380px', flexShrink: 0, padding: '32px 28px',
          background: 'var(--bg-white)', borderRight: '1px solid var(--border)',
          display: 'flex', flexDirection: 'column', justifyContent: 'space-between'
        }}>
          {/* Top section */}
          <div>
            {/* Headline */}
            <div style={{ marginBottom: '28px' }}>
              <p style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '0.2em', textTransform: 'uppercase', color: 'var(--teal)', marginBottom: '10px' }}>
                AI Division
              </p>
              <h1 style={{ fontSize: '24px', fontWeight: 800, lineHeight: 1.25, color: 'var(--text-heading)', marginBottom: '12px' }}>
                Intelligent Automation.{' '}
                <span style={{ color: 'var(--teal)' }}>Strategic AI.</span>{' '}
                Real Business Impact.
              </h1>
              <p style={{ fontSize: '14px', color: 'var(--text-body)', lineHeight: 1.6 }}>
                AI-driven analytics, robotic process automation, and intelligent quality assurance — delivering measurable ROI from day one.
              </p>
            </div>

            {/* Use case mini cards */}
            <div style={{ marginBottom: '24px' }}>
              <p style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: '10px' }}>
                Core Capabilities
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {useCases.map((uc, i) => (
                  <div key={i} style={{
                    display: 'flex', alignItems: 'center', gap: '10px', padding: '12px 14px',
                    background: 'var(--bg)', borderRadius: '8px', border: '1px solid var(--border)'
                  }}>
                    <uc.icon style={{ width: '18px', height: '18px', color: 'var(--teal)', flexShrink: 0 }} />
                    <div>
                      <span style={{ fontSize: '14px', fontWeight: 600, color: 'var(--text-heading)' }}>{uc.title}</span>
                      <p style={{ fontSize: '12px', color: 'var(--text-body)', lineHeight: 1.5, marginTop: '2px' }}>{uc.desc}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Impact Stats */}
            <div style={{ marginBottom: '24px' }}>
              <p style={{ fontSize: '11px', fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: '12px' }}>
                Impact at a Glance
              </p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px' }}>
                {[
                  { value: '10+', label: 'Industries' },
                  { value: '50+', label: 'Processes' },
                  { value: '3×', label: 'Avg. ROI' },
                ].map((stat, i) => (
                  <div key={i} style={{ textAlign: 'center', padding: '12px 8px', background: 'var(--bg)', borderRadius: '8px', border: '1px solid var(--border)' }}>
                    <div style={{ fontSize: '20px', fontWeight: 800, color: 'var(--teal)' }}>{stat.value}</div>
                    <div style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px' }}>{stat.label}</div>
                  </div>
                ))}
              </div>
            </div>

            {/* Website link */}
            <a href="https://www.chiacon.com" target="_blank" rel="noopener noreferrer"
              style={{
                display: 'block', padding: '12px 14px', borderRadius: '8px',
                background: 'var(--navy)', color: 'white', textDecoration: 'none',
                fontSize: '12px', fontWeight: 500, textAlign: 'center',
                transition: 'opacity 0.2s'
              }}
              onMouseOver={(e) => e.currentTarget.style.opacity = '0.85'}
              onMouseOut={(e) => e.currentTarget.style.opacity = '1'}
            >
              Visit chiacon.com →
            </a>
          </div>

          {/* Footer */}
          <div style={{ borderTop: '1px solid var(--border)', paddingTop: '12px' }}>
            <p style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
              © {new Date().getFullYear()} Chiacon Consulting
            </p>
          </div>
        </div>

        {/* ===== RIGHT PANEL — AI DEMO ===== */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
          {/* Demo Header + Input */}
          <div style={{ padding: '24px 32px 0', flexShrink: 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Sparkles style={{ width: '16px', height: '16px', color: 'var(--teal)' }} />
                <span style={{ fontSize: '12px', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--teal)' }}>
                  Live AI Demo
                </span>
              </div>
              {result && (
                <div style={{ display: 'flex', gap: '6px' }}>
                  <button onClick={() => { setResult(null); setInput(''); setError('') }}
                    style={{ display: 'flex', alignItems: 'center', gap: '5px', padding: '7px 14px', borderRadius: '7px', fontSize: '12px', fontWeight: 600, background: 'var(--bg-white)', color: 'var(--text-heading)', border: '1px solid var(--border-strong)', cursor: 'pointer', transition: 'all 0.2s', fontFamily: 'inherit', boxShadow: 'var(--shadow-sm)' }}>
                    <RotateCcw style={{ width: '12px', height: '12px' }} /> New Analysis
                  </button>
                  <CopyButton data={result} />
                </div>
              )}
            </div>
            <h2 style={{ fontSize: '22px', fontWeight: 700, color: 'var(--text-heading)', marginBottom: '4px' }}>
              AI Use Case Generator
            </h2>
            <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '16px' }}>
              Describe a business challenge. Get a strategic AI implementation roadmap in seconds.
            </p>

            {/* Input */}
            <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
              <input
                type="text" value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && !loading && handleSubmit()}
                placeholder="e.g. FMCG company struggling with reporting..."
                disabled={loading}
                style={{
                  flex: 1, background: 'var(--bg-white)', border: '1px solid var(--border)',
                  color: 'var(--text-heading)', padding: '10px 14px', borderRadius: '8px',
                  fontSize: '13px', outline: 'none', fontFamily: 'inherit',
                  transition: 'border-color 0.2s'
                }}
                onFocus={(e) => e.target.style.borderColor = 'var(--teal)'}
                onBlur={(e) => e.target.style.borderColor = 'var(--border)'}
              />
              <button onClick={() => handleSubmit()} disabled={loading || !input.trim()} className="btn-primary" style={{ padding: '10px 20px', fontSize: '13px' }}>
                {loading ? <Loader2 style={{ width: '14px', height: '14px' }} className="animate-spin" /> : <Send style={{ width: '14px', height: '14px' }} />}
                <span>{loading ? 'Analyzing...' : 'Analyze'}</span>
              </button>
            </div>

            {/* Quick prompts */}
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '16px' }}>
              {quickPrompts.map((p, i) => (
                <button key={i} onClick={() => handleQuickPrompt(p)} disabled={loading} className="chip">{p.label}</button>
              ))}
            </div>

            {/* Error */}
            {error && (
              <div style={{ padding: '10px 14px', borderRadius: '8px', fontSize: '12px', background: '#fef2f2', border: '1px solid #fecaca', color: 'var(--red)', marginBottom: '12px' }}>
                ⚠️ {error}
              </div>
            )}
          </div>

          {/* Results Area (scrollable) */}
          <div className="results-scroll" style={{ flex: 1, overflow: 'auto', padding: '0 32px 24px' }}>
            {loading && <LoadingSkeleton />}
            <ResultCards data={result} />
            {!loading && !result && !error && (
              <div style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                height: '100%', color: 'var(--text-muted)', textAlign: 'center'
              }}>
                <Sparkles style={{ width: '40px', height: '40px', color: 'var(--border)', marginBottom: '16px' }} />
                <p style={{ fontSize: '14px', fontWeight: 500 }}>Enter a business problem above</p>
                <p style={{ fontSize: '12px', marginTop: '4px' }}>or click one of the example prompts to see the AI in action</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
